language: cpp
sudo: required

# caching of the build dir (which is large, so large timeout (3 minute default))
# inspired from https://blog.esciencecenter.nl/travis-caching-and-incremental-builds-6518b89ee889
cache:
  timeout: 2000
  directories:
  - ../build  # the build directory

git:
  depth: 50

notifications:
  email: false
  
env:
  global:
    - HOMEBREW_NO_AUTO_UPDATE=1

matrix:
  fast_finish: true
  include:
  - env: BUILD_TYPE=Release BUILD_TARGET=package
    os: osx
    osx_image: xcode10
  allow_failures:
  - env: BUILD_TYPE=Release BUILD_TARGET=package
    os: osx
    osx_image: xcode10

install:
  - cmake --version
  - brew install ninja
  - brew install coreutils # for timeout
  - brew install findutils # for find
  - brew install qt
  - export PATH="/usr/local/opt/qt/bin:$PATH"

before_script:
  - find /usr/local/opt/python3/Frameworks/Python.framework/Versions -iname '*.app' | xargs rm -rf
  - mkdir -p "${TRAVIS_BUILD_DIR}/../build"
  - cd "${TRAVIS_BUILD_DIR}"
  - |
    if [[ -f ../build/mtimes.txt ]]
    then
      # restore modification times for the git repo
      while read mtime file; do gtouch -c -m -t "${mtime}" ${file}; done < ../build/mtimes.txt
     
      # touch changed git files to trigger their rebuild
      if [[ -f ../build/prev_commit.txt ]]
      then
        read prev_commit < ../build/prev_commit.txt 
        changed_files=`git diff --name-only ${prev_commit} HEAD`
        echo "Previously build based on commit ${prev_commit}."
        echo "Changed files since then: ${changed_files}" 
        if [[ -n ${changed_files} ]]
        then
          gtouch ${changed_files}
        fi
      fi
      cd "${TRAVIS_BUILD_DIR}/../build"
    else
      cd "${TRAVIS_BUILD_DIR}/../build"
      cmake -G Ninja -LA -DIVW_CMAKE_DEBUG=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DIVW_PACKAGE_PROJECT=ON -DIVW_PACKAGE_INSTALLER=ON -DIVW_UNITTESTS=OFF -DIVW_UNITTESTS_RUN_ON_BUILD=OFF ../inviwo
    fi
  
script:
  - gtimeout 40m cmake --build . --target ${BUILD_TARGET}


before_cache:
  - cd "${TRAVIS_BUILD_DIR}"
  # Save the modification time for all the files in the git repo
  - gfind . -type f -fprintf ../build/mtimes.txt "%TY%Tm%Td%TH%TM %p\n"
  # Save the current git commit so we can compare the next time
  - git rev-parse HEAD > ../build/prev_commit.txt


before_deploy:
  - export DMG_FILE_NAME=$(gfind $TRAVIS_BUILD_DIR/build -maxdepth 1 -iname 'Inviwo*.dmg')
  - echo "DMG ${DMG_FILE_NAME}"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "Ld1w6s5Dw/jyY7sIOBLlhRN5/bJ4P5BI4uQiTQ1ClNbH8+0U1qEs7R5IAS1La0RRW6X8UFIwbqV+oK1AJ/XWAtwepa9H1pGpLcdDSiHbqFK1O2inPGz7uFM+ttnKb0Gs/I3Dl+Ea2ufIk0QoVTOtcz5lYKPYvYPQXKeox7egECEGwtI0MqDyg2rI1TyGOQOb1fiLRt+ZzHSC1xdQMu8DaHn830mpv/jrYK0mU/jRUi1cPzZ0b3Al1ogg+Dn4XstPht5Fm6a32U4DsW39OAoMijRE4kVisfM//Q/RkpguGGRG70u5wzkMlZCLmjnMHbsqReV2hvQI6WOKCo0Sm0cyCqp7gc20Hn43Dw3WLZjQsdTdJwhMZKE8Ja+33CMxUjeaYsJfDfWTRgKpL3W2nFhIWrJOSEitO1cBJApZkZ4baDhqWTyuzoLASyrdfRS3vZc5i9ihq6mJhFQXH151fH60VDAFvFlDDzs83R2PaQ+5kAql0ni3Umik3Z4VoELFx6lPnKKNG1NZ/gqPopIJU4WaxGgH0qllgglOYKfOeIDfnYZOjXkzoRR/TAdaA2rJbb8+WzcROT5JgzDmB0qToqxbZOxKJcn+m1RzwZ/8XiEW9xXisMwzVKQmezvBAv9avHO+Y8DEGiTJYwezCpjglRiPXEs5MNllouTF7jxAiOEE0Zc="
  file: "${DMG_FILE_NAME}"
  overwrite: true # true to overwrite files in an existing release; default is false which will fail deployment if the release already exists on GitHub.
  on:
    repo: inviwo/inviwo
    tags: true
    condition: '"${TRAVIS_OS_NAME}" == osx'
